[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.backends._legacy:_Backend"

[project]
name = "easy-shermo"
version = "2.0.0"
description = "全自动批处理 Shermo 热力学计算的 Python 工具"
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.10"

authors = [
    { name = "Kimariyb", email = "kimariyb@163.com" },
]
dependencies = [
    "pyyaml>=6.0",
]

[project.urls]
Homepage = "https://github.com/kimariyb/easy-shermo"

[project.scripts]
easy-shermo = "easy_shermo.cli:main"
