# The path to the Shermo executable file.
shermo_path: "D:\\environment\\Shermo\\Shermo.exe"
# The program for performing a single point calculation task. 1. gaussian; 2. orca
sp_file: 2
# Treatment of low frequencies. 0: Harmonic. 1: Raising low frequencies. 2: Grimme's entropy interpolation
ilow_freq: 2
# Frequency scale factor for ZPE
scl_zpe: 0.9882
# Frequency scale factor for U(T)-U(0) (the same as that for H(T)-H(0))
scl_heat: 1.0062
# Frequency scale factor for S(T)
scl_s: 1.0104
# Frequency scale factor for heat capacity
scl_cv: 1.0
# in K. By specifying lower, upper limits and stepsize, e.g. 50,200,10, it can be scanned
temperature: 298.15
# in atm. By specifying lower, upper limits and stepsize, e.g. 0.5,20,0.1, it can be scanned
pressure: 1.0
