from service.excutor import create_files


def welcome():
    """
    Print a welcome message with information about the script.
    :return: None
    """
    hello = """
Easy Shermo: A python script to automate the use of Shermo
Version 1.0.0  Release date: 2023-Jul
Developer: Kimariyb (kimariyb@163.com)
Address: XiaMen University, School of Electronic Science and Engineering
Official website: https://github.com/kimariyb/easy-shermo

This script automates the use of Shermo, a program for calculating molecular thermochemistry properties. 
It reads the necessary information from output files generated by quantum chemistry programs and 
calculates various thermodynamic properties based on the ideal gas assumption. 

To use this script, you need to provide a configuration file that specifies the location of the Shermo 
program and other settings. The script will read the configuration file and use it to run Shermo on 
all the output files in the specified directory, with the specified energy levels.

For more information, please refer to the documentation on the official website.
    """
    print(hello)
    input("Please press Enter to continue.")



